### ISSUE TITLE
Rating: Mouse dragging for star selection

### ISSUE THREAD

**Issue by ryyppy** [belle-ui/elm-belle#8]
Instead of only allowing click events, it would be cool to register a mouse-down & drag across the rating stars.

**Comment by nikgraf** [comment]
👍 we can take some inspiration from React Belle

btw for touch events it is even more important 😄 

@terezka if I remember correctly you wanted to take up on this?!?

**Comment by terezka** [comment]
@nikgraf Yes, I'd love to!
